// packages/atom.io/src/react/store-context.tsx
import type { RootStore } from "atom.io/internal"
import { IMPLICIT } from "atom.io/internal"
import { createContext } from "react"

declare global {
	var ATOM_IO_REACT_STORE_CONTEXT: React.Context<RootStore> | undefined
}

// Reuse the context across physical package copies, like the implicit store.
export const StoreContext: React.Context<RootStore> =
	(globalThis.ATOM_IO_REACT_STORE_CONTEXT ??= createContext(IMPLICIT.STORE))

export const StoreProvider: React.FC<{
	children: React.ReactNode
	store?: RootStore
}> = ({ children, store = IMPLICIT.STORE }) => (
	<StoreContext.Provider value={store}>{children}</StoreContext.Provider>
)

// packages/atom.io/src/solid/store-context.ts
import type { RootStore } from "atom.io/internal"
import { IMPLICIT } from "atom.io/internal"
import type { Context, FlowProps, JSX } from "solid-js"
import { createContext } from "solid-js"

declare global {
	var ATOM_IO_SOLID_STORE_CONTEXT: Context<RootStore> | undefined
}

// Reuse the context across physical package copies, like the implicit store.
export const StoreContext: Context<RootStore> =
	(globalThis.ATOM_IO_SOLID_STORE_CONTEXT ??= createContext(IMPLICIT.STORE))

export function StoreProvider({
	children,
	store = IMPLICIT.STORE,
}: FlowProps<{
	store?: RootStore
}>): JSX.Element {
	return StoreContext.Provider({ value: store, children })
}
