// packages/atom.io/src/solid/use-o.ts
import type { ReadableFamilyToken, ReadableToken, ViewOf } from "atom.io"
import type { Canonical } from "atom.io/foundations/canonical"
import { arbitrary, getFromStore, subscribeToState } from "atom.io/internal"
import { useContext } from "solid-js"

import { parseStateOverloads } from "./parse-state-overloads.ts"
import { StoreContext } from "./store-context.ts"
import { useSyncExternalStore } from "./use-sync-external-store-solid.ts"

export function useO<T, E = never>(
	token: ReadableToken<T, any, E>,
): () => ViewOf<E | T>

export function useO<T, K extends Canonical, E = never>(
	token: ReadableFamilyToken<T, K, E>,
	key: NoInfer<K>,
): () => ViewOf<E | T>

export function useO<T, K extends Canonical, E = never>(
	...params:
		| [ReadableFamilyToken<T, K, E>, NoInfer<K>]
		| [ReadableToken<T, any, E>]
): () => ViewOf<E | T> {
	const store = useContext(StoreContext)
	const token = parseStateOverloads(store, ...params)
	const id = arbitrary()
	const sub = (dispatch: () => void) =>
		subscribeToState<T, E>(store, token, `use-o:${id}`, dispatch)
	const get = () => getFromStore(store, token)
	return useSyncExternalStore<ViewOf<E | T>>(sub, get)
}

// packages/atom.io/src/react/use-o.ts
import type { ReadableFamilyToken, ReadableToken, ViewOf } from "atom.io"
import type { Canonical } from "atom.io/foundations/canonical"
import { getFromStore, subscribeToState } from "atom.io/internal"
import {
	useCallback,
	useContext,
	useId,
	useRef,
	useState,
	useSyncExternalStore,
} from "react"

import { parseStateOverloads } from "./parse-state-overloads.ts"
import { StoreContext } from "./store-context.tsx"
import { useSingleEffect } from "./use-single-effect.ts"

export function useO<T, E = never>(
	token: ReadableToken<T, any, E>,
): ViewOf<E | T>

export function useO<T, K extends Canonical, E = never>(
	token: ReadableFamilyToken<T, K, E>,
	key: NoInfer<K>,
): ViewOf<E | T>

export function useO<T, K extends Canonical, E = never>(
	...params:
		| [ReadableFamilyToken<T, K, E>, NoInfer<K>]
		| [ReadableToken<T, any, E>]
): ViewOf<E | T> {
	const store = useContext(StoreContext)
	const token = parseStateOverloads(store, ...params)
	const id = useId()

	if (
		token.type === `mutable_atom` ||
		token.type === `readonly_held_selector` ||
		token.type === `writable_held_selector`
	) {
		const [, dispatch] = useState<number>(0)
		const valueRef = useRef<ViewOf<E | T>>(getFromStore(store, token))
		useSingleEffect(() => {
			const unsub = subscribeToState<T, E>(
				store,
				token,
				`use-o:${id}`,
				({ newValue }) => {
					valueRef.current = newValue
					dispatch((c) => c + 1)
				},
			)
			return unsub
		}, [token.key])
		return valueRef.current
	}

	const sub = useCallback(
		(dispatch: () => void) =>
			subscribeToState<T, E>(store, token, `use-o:${id}`, dispatch),
		[token.key],
	)
	const get = useCallback(() => getFromStore(store, token), [token.key])
	return useSyncExternalStore<ViewOf<E | T>>(sub, get, get)
}
