// packages/atom.io/docs/source/exhibits/solid/use-timeline-family.tsx
/** @jsxImportSource solid-js */
import { useTL } from "atom.io/solid"
import type { JSX } from "solid-js"

import { glyphTimelines } from "../core/timeline/create-a-timeline-family.ts"

export function GlyphHistory(props: { glyphId: string }): JSX.Element {
	const history = useTL(glyphTimelines, props.glyphId)

	return (
		<>
			<span>
				{history().at} / {history().length}
			</span>
			<button type="button" onClick={history().undo}>
				undo
			</button>
			<button type="button" onClick={history().redo}>
				redo
			</button>
		</>
	)
}

// packages/atom.io/docs/source/exhibits/react/use-timeline-family.tsx
import { useTL } from "atom.io/react"

import { glyphTimelines } from "../core/timeline/create-a-timeline-family.ts"

export function GlyphHistory(props: { glyphId: string }): React.JSX.Element {
	const { at, length, undo, redo, clear } = useTL(glyphTimelines, props.glyphId)

	return (
		<>
			<span>
				{at} / {length}
			</span>
			<button type="button" disabled={at === 0} onClick={undo}>
				undo
			</button>
			<button type="button" disabled={at === length} onClick={redo}>
				redo
			</button>
			<button type="button" onClick={clear}>
				clear history
			</button>
		</>
	)
}
